#!/usr/bin/env python3
"""
Trace: Does next_code increment after dictionary fills?
Clarify the continue vs normal iteration flow
"""

print("="*80)
print("TRACING: What happens iteration by iteration")
print("="*80)
print()

print("Setup: Dictionary just filled, next_code = 512")
print()

print("="*80)
print("ITERATION 1: Encoder sends NORMAL code")
print("="*80)
print()
print("Encoder: Outputs existing code 200 (from dictionary)")
print()
print("Decoder:")
print("  1. Read codeword = 200")
print("  2. if codeword == EVICT_SIGNAL: (200 == 511? NO)")
print("  3. Decode: current = dictionary[200]")
print("  4. Output: current")
print("  5. Add new entry:")
print()
print("     WITHOUT CHECK:")
print("       dictionary[512] = prev + current[0]  # DEAD ENTRY!")
print("       next_code = 513")
print()
print("     WITH CHECK:")
print("       if next_code < EVICT_SIGNAL: (512 < 511 is FALSE)")
print("       Skip add")
print("       next_code stays at 512")
print()

print("="*80)
print("ITERATION 2: Encoder needs to add new entry (triggers eviction)")
print("="*80)
print()
print("Encoder: Dictionary full, needs to add 'newdata'")
print("  - Evicts LRU entry (code 300)")
print("  - Sends: [EVICT_SIGNAL][300]['newdata']")
print()
print("Decoder:")
print("  1. Read codeword = 511 (EVICT_SIGNAL)")
print("  2. if codeword == EVICT_SIGNAL: YES")
print("  3. evict_code = 300")
print("  4. new_entry = 'newdata'")
print("  5. dictionary[300] = 'newdata'")
print("  6. continue  # <-- SKIPS EVERYTHING BELOW")
print()
print("     Lines skipped by continue:")
print("       - Decode codeword")
print("       - Output")
print("       - Add new entry (dictionary[next_code] = ...)")
print("       - next_code increment")
print()
print("     WITHOUT CHECK: next_code stays at 513")
print("     WITH CHECK: next_code stays at 512")
print()

print("="*80)
print("ITERATION 3: Encoder sends NORMAL code again")
print("="*80)
print()
print("Encoder: Outputs existing code 400")
print()
print("Decoder:")
print("  1. Read codeword = 400")
print("  2. if codeword == EVICT_SIGNAL: (400 == 511? NO)")
print("  3. Decode: current = dictionary[400]")
print("  4. Output: current")
print("  5. Add new entry:")
print()
print("     WITHOUT CHECK:")
print("       dictionary[513] = prev + current[0]  # ANOTHER DEAD ENTRY!")
print("       next_code = 514")
print()
print("     WITH CHECK:")
print("       if next_code < EVICT_SIGNAL: (512 < 511 is FALSE)")
print("       Skip add")
print("       next_code stays at 512")
print()

print("="*80)
print("THE KEY INSIGHT")
print("="*80)
print()
print("After dictionary fills, encoder sends:")
print("  - MOSTLY normal codes (existing dictionary entries)")
print("  - OCCASIONALLY EVICT_SIGNAL (only when adding new entries)")
print()
print("On NORMAL iterations (most iterations):")
print("  - continue is NOT executed")
print("  - Code reaches the 'Add new entry' section")
print("  - WITHOUT check: next_code increments (512, 513, 514, ...)")
print("  - WITH check: next_code stays frozen at 512")
print()
print("On EVICT_SIGNAL iterations (rare):")
print("  - continue IS executed")
print("  - Skips everything including increment")
print("  - next_code stays same")
print()
print("Result:")
print("  WITHOUT check: next_code grows on normal iterations")
print("  WITH check: next_code stays frozen forever at 512")
print()

print("="*80)
print("FREQUENCY")
print("="*80)
print()
print("Typical pattern after dict fills:")
print("  - 100 normal codes (output existing entries)")
print("  - 1 EVICT_SIGNAL (add new entry)")
print("  - 100 normal codes")
print("  - 1 EVICT_SIGNAL")
print("  - ...")
print()
print("So WITHOUT check:")
print("  next_code increments ~100 times, stays same once")
print("  Result: 512, 513, 514, ..., 611, 611, 612, ..., 711, ...")
print("  Keeps growing!")
print()
print("="*80)
